export const projects = [
  {
    id: "1",
    title: "BariSathi (Smart Rental & Housing Solution)",
    shortDescription:
      "Full-stack web application connecting landlords, tenants, and an admin in a smart rental-housing platform.",
    description:
      "BariSathi is a full-stack web application connecting landlords, tenants, and an admin in a smart rental-housing platform. Landlords can post and manage rentals; tenants can browse, filter, and request rentals; admins oversee users and listings. Secure JWT auth, role-based access control, and Stripe payment options are built in.",
    images: [
      "/barisathi/home.png",
      "/barisathi/listings.png",
      "/barisathi/tenant-request.png",
      "/barisathi/admin-dashboard.png",
    ],
    coreFeatures: [
      "Landlords can post and manage rental listings",
      "Tenants can browse, filter, and request rentals",
      "Admins oversee users and listings",
      "Secure JWT authentication and role-based access",
      "Stripe payment integration",
      "Email notifications for approvals and payments",
    ],
    coreTechnology: [
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Radix UI",
      "Framer Motion",
      "Node.js",
      "Express",
      "MongoDB",
      "Mongoose",
      "Zod",
      "JWT",
      "Stripe API",
    ],
    challengesFaced: [
      "Implementing secure JWT auth and role-based access control",
      "Integrating Stripe payment options",
      "Designing a robust admin dashboard",
      "Ensuring data consistency across user roles",
    ],
    futurePlans: [
      "Add advanced search filters for rentals",
      "Implement real-time chat between landlords and tenants",
      "Add property image gallery upload",
      "Enable multi-currency payment support",
    ],
    versionInfo: {
      "Next.js": "15.2.0",
      React: "^19.0.0",
      TypeScript: "^5",
      "Tailwind CSS": "4",
      "@stripe/stripe-js": "^7.0.0",
      "@stripe/react-stripe-js": "^3.6.0",
      "Node.js": "20",
    },
    liveLink: "https://barisathi.vercel.app",
    repositoryLink: "https://github.com/shahadathhs/barisathi",
  },
  {
    id: "2",
    title: "Bike Shop (E-commerce Application)",
    shortDescription:
      "Full-stack Bike Shop application enabling users to browse and purchase bicycles, with an admin dashboard for managing products, orders, and users.",
    description:
      "Bike Shop is a full-stack web application that enables users to browse and purchase bicycles, while providing administrators with a robust dashboard for managing products, orders, and users. It features secure JWT-based authentication, role-based access control, and Stripe integration for payment processing.",
    images: [
      "/bike-shop/home.png",
      "/bike-shop/products.png",
      "/bike-shop/admin-dashboard.png",
    ],
    coreFeatures: [
      "Responsive frontend with carousel banners and detailed product pages",
      "Secure user registration and login with JWT",
      "Role-based dashboards for customers and administrators",
      "Full CRUD operations for bike products",
      "Image uploads via Cloudinary",
      "Filtering, search, and pagination for product listings",
      "Stripe payment integration with real-time stock checks",
      "Order tracking and analytics in admin dashboard",
    ],
    coreTechnology: [
      "React",
      "TypeScript",
      "React Router v7",
      "Tailwind CSS",
      "Node.js",
      "Express",
      "MongoDB",
      "Mongoose",
      "Zod",
      "JWT",
      "Stripe API",
      "Vite",
    ],
    challengesFaced: [
      "Implementing secure authentication and role-based access",
      "Integrating Stripe checkout with real-time stock validation",
      "Optimizing image uploads and pagination performance",
      "Designing comprehensive admin analytics dashboard",
    ],
    futurePlans: [
      "Add AI-driven product recommendations",
      "Integrate Notifications API for real-time notifications for order updates",
      "Add internationalization support",
    ],
    versionInfo: {
      React: "^19.0.0",
      TypeScript: "^5.7.2",
      "Tailwind CSS": "4.0.0",
      Vite: "^5.4.11",
      "Node.js": "20",
      Express: "^4.21.2",
      "Stripe API": "^17.6.0",
    },
    liveLink: "https://bike-shop-client-kappa.vercel.app",
    repositoryLink: "https://github.com/shahadathhs/bike-shop",
  },
  {
    id: "3",
    title: "Password Generator NPM Package",
    shortDescription:
      "A customizable, lightweight, and secure password generator NPM package for JS/TS.",
    description:
      "This NPM package provides secure, client-side password and passphrase generation with extensive customization options. It supports length, character sets, multiple password generation, and error handling, as well as customizable passphrase generation for memorable security.",
    images: ["/password/npm.png", "/password/git.png"],
    coreFeatures: [
      "Customizable password length and charset",
      "Multiple password generation",
      "Passphrase generation with customizable word lists",
      "Built-in error handling with descriptive messages",
      "Zero dependencies",
      "TypeScript definitions",
    ],
    coreTechnology: ["JavaScript", "TypeScript", "Jest", "ESLint", "npm"],
    challengesFaced: [
      "Ensuring cryptographic randomness in browsers",
      "Building a minimal bundle size",
      "Maintaining type safety across JS and TS",
      "Writing thorough unit tests with Jest",
    ],
    futurePlans: [
      "Add WebAssembly support for faster generation",
      "Publish benchmark comparisons",
      "Integrate with CI pipelines for automated releases",
      "Add customizable passphrase templates",
    ],
    versionInfo: {
      "@types/jest": "^29.5.14",
      eslint: "^9.18.0",
      jest: "^29.7.0",
      "ts-jest": "^29.2.5",
      "ts-node": "^10.9.2",
      tsup: "^8.3.5",
      typescript: "^5.7.3",
      npm: "10.4.1",
    },
    liveLink: "https://www.npmjs.com/package/generate-password-in-client-side",
    repositoryLink: "https://github.com/shahadathhs/generate-password",
  },
  {
    id: "4",
    title: "Turborepo Starter Template with pnpm",
    shortDescription:
      "Monorepo starter template configured with pnpm and Turborepo, preconfigured with ESLint, TypeScript, Prettier, and shadcn/ui components.",
    description:
      "A Turborepo starter template for monorepo workflows using pnpm as the package manager and Turborepo for task orchestration. It includes modern tooling like ESLint, TypeScript, Prettier, and a sample shadcn/ui component library, demonstrating apps (Express REST API, Next.js web, React Router web) and shared packages.",
    images: [
      "/turborepo/git.png",
    ],
    coreFeatures: [
      "Monorepo structure with apps and packages directories",
      "Preconfigured ESLint, TypeScript, and Prettier configurations",
      "shadcn/ui component library package",
      "pnpm workspace integration",
      "Turborepo task orchestration with caching and parallel execution",
    ],
    coreTechnology: [
      "pnpm",
      "Turborepo",
      "TypeScript",
      "ESLint",
      "Prettier",
      "shadcn/ui",
      "Express.js",
      "Next.js",
      "React Router v7",
    ],
    challengesFaced: [
      "Learning pnpm workspace commands",
      "Configuring Turborepo tasks and caching",
      "Maintaining consistent configs across packages",
      "Integrating shadcn/ui with multiple frameworks",
    ],
    futurePlans: [
      "Integrate CI pipelines for build caching",
      "Add automated code generation tasks",
      "Enhance custom ESLint rules",
    ],
    versionInfo: {
      pnpm: "10.4.1",
      turbo: "1.9.4",
      TypeScript: "5.7.3",
      ESLint: "^9.18.0",
      Prettier: "^3.4.2",
    },
    repositoryLink: "https://github.com/shahadathhs/turborepo-starter",
  },
];
